# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180507_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='ticket',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
