# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTicket',
            new_name='UserTicketModel',
        ),
    ]
