# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180508_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticketmodel',
            name='out_time',
            field=models.DateTimeField(),
        ),
    ]
