# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180508_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='c_num',
            field=models.IntegerField(default=1),
        ),
    ]
